package com.buss.common.entity;
// Generated 2016-2-24 14:10:58 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HxArticleDetail generated by hbm2java
 */
@Entity
@Table(name = "hx_article_detail", catalog = "hxclub")
public class HxArticleDetail implements java.io.Serializable {

	private long id;
	private String content;
	private Long count;
	private Date createTime;
	private Date updateTime;
	private Integer levelclass;
	private HxArticle hxArticle;

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "content", length = 65535)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "count")
	public Long getCount() {
		return this.count;
	}

	public void setCount(Long count) {
		this.count = count;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@OneToOne(optional = false)
	@JoinColumn(name = "id", referencedColumnName = "id", unique = true)
	public HxArticle getHxArticle() {
		return hxArticle;
	}

	public void setHxArticle(HxArticle hxArticle) {
		this.hxArticle = hxArticle;
	}

	@Column(name = "levelclass")
	public Integer getLevelclass() {
		return levelclass;
	}

	public void setLevelclass(Integer levelclass) {
		this.levelclass = levelclass;
	}

}
