package com.buss.common.entity;
// Generated 2016-3-29 10:56:41 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HxFile generated by hbm2java
 */
@Entity
@Table(name = "hx_file", catalog = "hxclub")
public class HxFile implements java.io.Serializable {

	private String id;
	private String name;
	private String title;
	/** 文件类型（1入会申请资料2入会协议3缴费回执单。。） */
	private java.lang.Integer filetype;
	/** 核审状态 */
	private java.lang.Integer checkstatus;

	private String downloadUrl;
	private Date createtime;
	private Date updatetime;
	private Set<HxFileUser> hxFileUsers = new HashSet<HxFileUser>(0);

	/**
	 * 方法: 取得java.lang.Integer
	 * 
	 * @return: java.lang.Integer 核审状态
	 */
	@Column(name = "CHECKSTATUS", nullable = true, precision = 10, scale = 0)
	public java.lang.Integer getCheckstatus() {
		return this.checkstatus;
	}

	/**
	 * 方法: 设置java.lang.Integer
	 * 
	 * @param: java.lang.Integer
	 *             核审状态
	 */
	public void setCheckstatus(java.lang.Integer checkstatus) {
		this.checkstatus = checkstatus;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "title")
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "download_url")
	public String getDownloadUrl() {
		return this.downloadUrl;
	}

	public void setDownloadUrl(String downloadUrl) {
		this.downloadUrl = downloadUrl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createtime", length = 8)
	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updatetime", length = 8)
	public Date getUpdatetime() {
		return this.updatetime;
	}

	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hxFile")
	public Set<HxFileUser> getHxFileUsers() {
		return this.hxFileUsers;
	}

	public void setHxFileUsers(Set<HxFileUser> hxFileUsers) {
		this.hxFileUsers = hxFileUsers;
	}

	@Column(name = "FILETYPE", nullable = true, precision = 10, scale = 0)
	public java.lang.Integer getFiletype() {
		return filetype;
	}

	public void setFiletype(java.lang.Integer filetype) {
		this.filetype = filetype;
	}

}
