package com.buss.common.entity;
// Generated 2016-3-29 10:56:41 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.buss.member.entity.GeneralUserEntity;

/**
 * HxFileUser generated by hbm2java
 */
@Entity
@Table(name = "hx_file_user", catalog = "hxclub")
public class HxFileUser implements java.io.Serializable {

	private String id;
	private HxFile hxFile;
	private GeneralUserEntity hxUser;
	private Integer status;
	private Integer isDelete;

	public HxFileUser() {
	}

	public HxFileUser(String id) {
		this.id = id;
	}

	public HxFileUser(String id, HxFile hxFile, GeneralUserEntity hxUser, Integer status, Integer isDelete) {
		this.id = id;
		this.hxFile = hxFile;
		this.hxUser = hxUser;
		this.status = status;
		this.isDelete = isDelete;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "fid")
	public HxFile getHxFile() {
		return this.hxFile;
	}

	public void setHxFile(HxFile hxFile) {
		this.hxFile = hxFile;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "userid")
	public GeneralUserEntity getHxUser() {
		return this.hxUser;
	}

	public void setHxUser(GeneralUserEntity hxUser) {
		this.hxUser = hxUser;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "is_delete")
	public Integer getIsDelete() {
		return this.isDelete;
	}

	public void setIsDelete(Integer isDelete) {
		this.isDelete = isDelete;
	}

}
